Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,16 +23,15 @@ jobs:
       run: sudo apt-get install -y bash
 
 
-- name: Validate secrets
-  run: |
-    if [ -z "$FILE_TOKEN" ]; then echo "FILE_TOKEN is missing"; exit 1; fi
-    if [ -z "$PROFILE_REPO" ]; then echo "PROFILE_REPO is missing"; exit 1; fi
-    if [ -z "$BASE_URL" ]; then echo "BASE_URL is missing"; exit 1; fi
-  env:
-    FILE_TOKEN: ${{ secrets.FILE_TOKEN }}
-    PROFILE_REPO: ${{ secrets.PROFILE_REPO }}
-    BASE_URL: ${{ secrets.PATH }}
+    - name: Validate secrets
+      run: |
+        if [ -z "$FILE_TOKEN" ]; then echo "FILE_TOKEN is missing"; exit 1; fi
+        if [ -z "$PROFILE_REPO" ]; then echo "PROFILE_REPO is missing"; exit 1; fi
+        if [ -z "$BASE_URL" ]; then echo "BASE_URL is missing"; exit 1; fi
+      env:
+        FILE_TOKEN: ${{ secrets.FILE_TOKEN }}
+        PROFILE_REPO: ${{ secrets.PROFILE_REPO }}
+        BASE_URL: ${{ secrets.PATH }}
 
-    
     - name: Run the script
       run: node run.js
